ALTER TABLE inventory ADD COLUMN IF NOT EXISTS avg_cost NUMERIC(10,2);
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS unit_cost NUMERIC(10,2);
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS unit_cost NUMERIC(10,2);